# -*- coding: utf-8 -*-
"""HSN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ev-3njn8GFaCK7waGl8ZZFY45i7PGCN4
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Replace this with your uploaded file name
filename = list(uploaded.keys())[0]

# Load both sheets
hsn_df = pd.read_excel(filename, sheet_name=0, dtype=str)
sac_df = pd.read_excel(filename, sheet_name=1, dtype=str)

# Clean column names
hsn_df.columns = ['HSNCode', 'Description']
sac_df.columns = ['SACCode', 'SAC_Description']

# Strip whitespace
hsn_df['HSNCode'] = hsn_df['HSNCode'].str.strip()
sac_df['SACCode'] = sac_df['SACCode'].str.strip()

# Show sample data
hsn_df.head(), sac_df.head()

# HSN validation
def validate_hsn(code):
    result = {}
    if not code.isdigit():
        result['valid'] = False
        result['reason'] = 'Invalid format – must be numeric.'
    elif len(code) not in [2, 4, 6, 8]:
        result['valid'] = False
        result['reason'] = 'Invalid length – must be 2, 4, 6, or 8 digits.'
    elif code in hsn_df['HSNCode'].values:
        desc = hsn_df.loc[hsn_df['HSNCode'] == code, 'Description'].values[0]
        result['valid'] = True
        result['description'] = desc
    else:
        result['valid'] = False
        result['reason'] = 'HSN code not found in dataset.'
    return result

# SAC validation
def validate_sac(code):
    result = {}
    if not code.isdigit():
        result['valid'] = False
        result['reason'] = 'Invalid format – must be numeric.'
    elif len(code) < 2 or len(code) > 6:
        result['valid'] = False
        result['reason'] = 'Invalid length – must be between 2 and 6 digits.'
    elif code in sac_df['SACCode'].values:
        desc = sac_df.loc[sac_df['SACCode'] == code, 'SAC_Description'].values[0]
        result['valid'] = True
        result['description'] = desc
    else:
        result['valid'] = False
        result['reason'] = 'SAC code not found in dataset.'
    return result

# Interactive Input
code_type = input("Enter code type (HSN/SAC): ").strip().upper()
code_input = input("Enter one or more codes separated by commas: ")

codes = [c.strip() for c in code_input.split(",")]

print("\nValidation Results:\n")
for code in codes:
    if code_type == "HSN":
        result = validate_hsn(code)
    elif code_type == "SAC":
        result = validate_sac(code)
    else:
        print(f"Invalid code type: {code_type}")
        break

    print(f"Code: {code}")
    print(f"Result: {result}\n")

